AppBundle\Entity\Evento:
    type: entity
    table: eventos
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        descripcion:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        horario:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        fecha:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        organizadores:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: Organizadores
        lugar:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        direccion:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
