AppBundle\Entity\EventUsuario:
    type: entity
    table: event_usuario
    indexes:
        id_usuario:
            columns:
                - id_usuario
        id_evento:
            columns:
                - id_evento
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idEvento:
            targetEntity: Evento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_evento:
                    referencedColumnName: id
            orphanRemoval: false
        idUsuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
